# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_bluefield_2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16test_bluefield_2.proto\x12\x0etest_bluefield\";\n\tRectangle\x12\n\n\x02r1\x18\x01 \x01(\x05\x12\n\n\x02r2\x18\x02 \x01(\x05\x12\n\n\x02r3\x18\x03 \x01(\x05\x12\n\n\x02r4\>



_RECTANGLE = DESCRIPTOR.message_types_by_name['Rectangle']
_RECTANGLES = DESCRIPTOR.message_types_by_name['Rectangles']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Rectangle = _reflection.GeneratedProtocolMessageType('Rectangle', (_message.Message,), {
  'DESCRIPTOR' : _RECTANGLE,
  '__module__' : 'test_bluefield_2_pb2'
  # @@protoc_insertion_point(class_scope:test_bluefield.Rectangle)
  })
_sym_db.RegisterMessage(Rectangle)

Rectangles = _reflection.GeneratedProtocolMessageType('Rectangles', (_message.Message,), {
  'DESCRIPTOR' : _RECTANGLES,
  '__module__' : 'test_bluefield_2_pb2'
  # @@protoc_insertion_point(class_scope:test_bluefield.Rectangles)
  })
_sym_db.RegisterMessage(Rectangles)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'test_bluefield_2_pb2'
  # @@protoc_insertion_point(class_scope:test_bluefield.Empty)
  })
_sym_db.RegisterMessage(Empty)

_DETECTION = DESCRIPTOR.services_by_name['Detection']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037io.grpc.examples.test_bluefieldB\022TestBluefieldProtoP\001\242\002\002TB'
  _RECTANGLE._serialized_start=42
  _RECTANGLE._serialized_end=101
  _RECTANGLES._serialized_start=103
  _RECTANGLES._serialized_end=177
  _EMPTY._serialized_start=179
  _EMPTY._serialized_end=204
  _DETECTION._serialized_start=206
  _DETECTION._serialized_end=283
# @@protoc_insertion_point(module_scope)
