# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_bluefield.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14test_bluefield.proto\x12\x0etest_bluefield\";\n\tRectangle\x12\n\n\x02r1\x18\x01 \x01(\x05\x12\n\n\x02r2\x18\x02 \x01(\x05\x12\n\n\x02r3\x18\x03 \x01(\x05\x12\n\n\x02r4\x1>



_RECTANGLE = DESCRIPTOR.message_types_by_name['Rectangle']
_RECTANGLES = DESCRIPTOR.message_types_by_name['Rectangles']
_FRAMERECIVED = DESCRIPTOR.message_types_by_name['FrameRecived']
Rectangle = _reflection.GeneratedProtocolMessageType('Rectangle', (_message.Message,), {
  'DESCRIPTOR' : _RECTANGLE,
  '__module__' : 'test_bluefield_pb2'
  # @@protoc_insertion_point(class_scope:test_bluefield.Rectangle)
  })
_sym_db.RegisterMessage(Rectangle)

Rectangles = _reflection.GeneratedProtocolMessageType('Rectangles', (_message.Message,), {
  'DESCRIPTOR' : _RECTANGLES,
  '__module__' : 'test_bluefield_pb2'
  # @@protoc_insertion_point(class_scope:test_bluefield.Rectangles)
  })
_sym_db.RegisterMessage(Rectangles)

FrameRecived = _reflection.GeneratedProtocolMessageType('FrameRecived', (_message.Message,), {
  'DESCRIPTOR' : _FRAMERECIVED,
  '__module__' : 'test_bluefield_pb2'
  # @@protoc_insertion_point(class_scope:test_bluefield.FrameRecived)
  })
_sym_db.RegisterMessage(FrameRecived)

_DETECTION = DESCRIPTOR.services_by_name['Detection']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037io.grpc.examples.test_bluefieldB\022TestBluefieldProtoP\001\242\002\002TB'
  _RECTANGLE._serialized_start=40
  _RECTANGLE._serialized_end=99
  _RECTANGLES._serialized_start=101
  _RECTANGLES._serialized_end=160
  _FRAMERECIVED._serialized_start=162
  _FRAMERECIVED._serialized_end=193
  _DETECTION._serialized_start=195
  _DETECTION._serialized_end=279
# @@protoc_insertion_point(module_scope)
